# Abib
# Copyright (C) 2003–2026 <Contributors>
# SPDX-License-Identifier: GPL-3.0-or-later

# -*- coding: utf-8 -*-

"""Read-only access to the Strong's-number / original-language lookup data.

This service reads ``strongs.sqlite`` — a read-only database generated by
``tools/build_strongs_sqlite.py`` — and exposes the queries the UI needs for the
Strong's lookup feature:

  * :func:`get_tags_for_verse` — the Strong's-tagged words of a single verse,
    used to make words in the Bible text clickable/hoverable.
  * :func:`lookup_strongs` — the dictionary entry (lemma, transliteration,
    definitions, …) for a Strong's code, used by the popup/panel.
  * :func:`find_verses_by_strongs` — every verse in which a Strong's code
    occurs, used by "find all occurrences" / search-by-number.
  * :func:`tag_at` — resolve a clicked/hovered ``(verse_index, word_pos)``.

The database file lives next to Abib's other runtime data (mirroring
``gill.cmt.sqlite``) and is resolved via ``Path(sh.str_cwd) / "strongs.sqlite"``.
If the file is missing the service degrades gracefully: :func:`is_available`
returns ``False`` and every query returns an empty result rather than raising,
so the UI can simply hide/grey the feature.

Schema (see ``tools/BUILD_STRONGS.md``)::

    word_tags(verse_index INTEGER, word_pos INTEGER, surface TEXT, strongs TEXT)
    strongs_dict(strongs TEXT PRIMARY KEY, lemma, translit, pronunciation,
                 short_def, long_def, language)
    meta(key TEXT PRIMARY KEY, value TEXT)

``verse_index`` is Abib's flat global verse index (0..``LAST_VERSE_IN_BIBLE``),
identical to the position used by ``sh.Info``.
"""

from __future__ import annotations

import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from abib.core import shared as sh

DB_FILENAME = "strongs.sqlite"

# Accepts 'H430', 'h0430', 'G3056', with or without leading zeros / whitespace.
_CODE_RE = re.compile(r"^\s*([HhGg])0*(\d+)\s*$")


@dataclass(frozen=True)
class WordTag:
    """One Strong's-tagged word occurrence within a verse."""

    verse_index: int
    word_pos: int
    surface: str
    strongs: str


@dataclass(frozen=True)
class StrongsEntry:
    """A single Strong's dictionary entry."""

    strongs: str
    lemma: str
    translit: str
    pronunciation: str
    short_def: str
    long_def: str
    language: str


def normalise_code(code: str) -> str | None:
    """Normalise a Strong's code to canonical ``H%04d`` / ``G%04d`` form.

    Returns ``None`` if *code* is not a recognisable Strong's number.
    """
    if not isinstance(code, str):
        return None
    m = _CODE_RE.match(code)
    if not m:
        return None
    letter = m.group(1).upper()
    return f"{letter}{int(m.group(2)):04d}"


class StrongsService:
    """Lazy, read-only accessor for ``strongs.sqlite``.

    A single instance can be shared across the application. The SQLite
    connection is opened lazily on first use and reused thereafter.
    """

    def __init__(self, db_path: Path | str | None = None) -> None:
        if db_path is None:
            db_path = Path(sh.str_cwd) / DB_FILENAME
        self._db_path = Path(db_path)
        self._conn: sqlite3.Connection | None = None
        self._checked_missing = False

    # --------- Connection helpers ---------
    def _ensure_conn(self) -> sqlite3.Connection | None:
        """Return an open connection, or ``None`` if the DB is unavailable."""
        if self._conn is not None:
            return self._conn
        if self._checked_missing:
            return None
        if not self._db_path.is_file():
            # Remember so we don't stat the filesystem on every call.
            self._checked_missing = True
            return None
        try:
            conn = sqlite3.connect(str(self._db_path))
            conn.row_factory = sqlite3.Row
            self._conn = conn
            return conn
        except sqlite3.Error:
            self._checked_missing = True
            return None

    def is_available(self) -> bool:
        """Return ``True`` if the Strong's database can be queried."""
        return self._ensure_conn() is not None

    def close(self) -> None:
        """Close the underlying connection, if any."""
        try:
            if self._conn is not None:
                self._conn.close()
        except sqlite3.Error:
            pass
        finally:
            self._conn = None

    # --------- Queries ---------
    def get_tags_for_verse(self, verse_index: int) -> list[WordTag]:
        """Return the Strong's-tagged words of *verse_index*, in reading order."""
        try:
            vi = int(verse_index)
        except (TypeError, ValueError):
            return []
        conn = self._ensure_conn()
        if conn is None:
            return []
        try:
            rows = conn.execute(
                "SELECT verse_index, word_pos, surface, strongs "
                "FROM word_tags WHERE verse_index = ? ORDER BY word_pos",
                (vi,),
            ).fetchall()
        except sqlite3.Error:
            return []
        return [
            WordTag(
                verse_index=int(r["verse_index"]),
                word_pos=int(r["word_pos"]),
                surface=str(r["surface"] or ""),
                strongs=str(r["strongs"] or ""),
            )
            for r in rows
        ]

    def tag_at(self, verse_index: int, word_pos: int) -> WordTag | None:
        """Resolve a single ``(verse_index, word_pos)`` to its :class:`WordTag`."""
        try:
            vi = int(verse_index)
            wp = int(word_pos)
        except (TypeError, ValueError):
            return None
        conn = self._ensure_conn()
        if conn is None:
            return None
        try:
            r = conn.execute(
                "SELECT verse_index, word_pos, surface, strongs "
                "FROM word_tags WHERE verse_index = ? AND word_pos = ?",
                (vi, wp),
            ).fetchone()
        except sqlite3.Error:
            return None
        if r is None:
            return None
        return WordTag(
            verse_index=int(r["verse_index"]),
            word_pos=int(r["word_pos"]),
            surface=str(r["surface"] or ""),
            strongs=str(r["strongs"] or ""),
        )

    def lookup_strongs(self, code: str) -> StrongsEntry | None:
        """Return the dictionary entry for a Strong's *code*, or ``None``."""
        norm = normalise_code(code)
        if norm is None:
            return None
        conn = self._ensure_conn()
        if conn is None:
            return None
        try:
            r = conn.execute(
                "SELECT strongs, lemma, translit, pronunciation, short_def, "
                "long_def, language FROM strongs_dict WHERE strongs = ?",
                (norm,),
            ).fetchone()
        except sqlite3.Error:
            return None
        if r is None:
            return None
        return StrongsEntry(
            strongs=str(r["strongs"] or ""),
            lemma=str(r["lemma"] or ""),
            translit=str(r["translit"] or ""),
            pronunciation=str(r["pronunciation"] or ""),
            short_def=str(r["short_def"] or ""),
            long_def=str(r["long_def"] or ""),
            language=str(r["language"] or ""),
        )

    def find_verses_by_strongs(self, code: str) -> list[int]:
        """Return the sorted, unique verse indices where *code* occurs."""
        norm = normalise_code(code)
        if norm is None:
            return []
        conn = self._ensure_conn()
        if conn is None:
            return []
        try:
            rows = conn.execute(
                "SELECT DISTINCT verse_index FROM word_tags "
                "WHERE strongs = ? ORDER BY verse_index",
                (norm,),
            ).fetchall()
        except sqlite3.Error:
            return []
        return [int(r["verse_index"]) for r in rows]

    def count_occurrences(self, code: str) -> int:
        """Return the total number of times *code* is tagged across the Bible."""
        norm = normalise_code(code)
        if norm is None:
            return 0
        conn = self._ensure_conn()
        if conn is None:
            return 0
        try:
            r = conn.execute(
                "SELECT COUNT(*) FROM word_tags WHERE strongs = ?", (norm,)
            ).fetchone()
        except sqlite3.Error:
            return 0
        if r is None:
            return 0
        return int(r[0])
