# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Find.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets


class UiDialog(object):
    def __init__(self):
        self.buttonBox = None
        self.frame = None
        self.frame_2 = None
        self.frame_3 = None
        self.radiobutton_1 = None
        self.radiobutton_2 = None
        self.radiobutton_3 = None
        self.radiobutton_4 = None
        self.radiobutton_5 = None
        self.radiobutton_6 = None
        self.buttonGroup = None
        self.buttonGroup_2 = None
        self.label = None
        self.label_1 = None
        self.label_2 = None
        self.pushButton_1 = None
        self.checkBox = None
        self.comboBox_1 = None
        self.comboBox_2 = None
        self.lineEdit_1 = None
        self.status_label = None

    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(400, 378)
        dialog.setWindowOpacity(1.0)
        self.frame = QtWidgets.QFrame(dialog)
        self.frame.setGeometry(QtCore.QRect(10, 240, 191, 91))
        self.frame.setMouseTracking(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setObjectName("frame")
        self.radiobutton_5 = QtWidgets.QRadioButton(self.frame)
        self.radiobutton_5.setGeometry(QtCore.QRect(10, 10, 171, 17))
        self.radiobutton_5.setChecked(True)
        self.radiobutton_5.setObjectName("radiobutton_5")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radiobutton_5)
        self.radiobutton_6 = QtWidgets.QRadioButton(self.frame)
        self.radiobutton_6.setGeometry(QtCore.QRect(10, 50, 171, 17))
        self.radiobutton_6.setObjectName("radiobutton_6")
        self.buttonGroup_2.addButton(self.radiobutton_6)
        self.label_1 = QtWidgets.QLabel(dialog)
        self.label_1.setGeometry(QtCore.QRect(20, 220, 181, 16))
        self.label_1.setObjectName("label_1")
        self.checkBox = QtWidgets.QCheckBox(dialog)
        self.checkBox.setGeometry(QtCore.QRect(20, 180, 361, 31))
        self.checkBox.setObjectName("checkBox")
        self.lineEdit_1 = QtWidgets.QLineEdit(dialog)
        self.lineEdit_1.setGeometry(QtCore.QRect(70, 10, 321, 21))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label.setObjectName("label")
        self.pushButton_1 = QtWidgets.QPushButton(dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(370, 10, 21, 21))
        self.pushButton_1.setObjectName("pushButton_1")
        self.frame_2 = QtWidgets.QFrame(dialog)
        self.frame_2.setGeometry(QtCore.QRect(220, 240, 171, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.comboBox_1 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_1.setGeometry(QtCore.QRect(10, 10, 151, 22))
        self.comboBox_1.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.NoInsert)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 50, 151, 22))
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.NoInsert)
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 220, 161, 20))
        self.label_2.setObjectName("label_2")
        self.radiobutton_1 = QtWidgets.QRadioButton(dialog)
        self.radiobutton_1.setGeometry(QtCore.QRect(20, 50, 361, 31))
        self.radiobutton_1.setTabletTracking(True)
        self.radiobutton_1.setChecked(True)
        self.radiobutton_1.setObjectName("radiobutton_1")
        self.buttonGroup = QtWidgets.QButtonGroup(dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radiobutton_1)
        self.radiobutton_2 = QtWidgets.QRadioButton(dialog)
        self.radiobutton_2.setGeometry(QtCore.QRect(20, 80, 361, 31))
        self.radiobutton_2.setObjectName("radiobutton_2")
        self.buttonGroup.addButton(self.radiobutton_2)
        self.radiobutton_3 = QtWidgets.QRadioButton(dialog)
        self.radiobutton_3.setGeometry(QtCore.QRect(20, 110, 361, 31))
        self.radiobutton_3.setObjectName("radiobutton_3")
        self.buttonGroup.addButton(self.radiobutton_3)
        self.radiobutton_4 = QtWidgets.QRadioButton(dialog)
        self.radiobutton_4.setGeometry(QtCore.QRect(20, 140, 361, 31))
        self.radiobutton_4.setObjectName("radiobutton_4")
        self.buttonGroup.addButton(self.radiobutton_4)
        self.frame_3 = QtWidgets.QFrame(dialog)
        self.frame_3.setGeometry(QtCore.QRect(10, 49, 381, 121))
        self.frame_3.setMouseTracking(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(dialog)
        self.buttonBox.setGeometry(QtCore.QRect(230, 340, 156, 23))
        self.buttonBox.setMouseTracking(True)
        self.buttonBox.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        buttons = (
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButtons(buttons))
        self.buttonBox.setProperty(".standardButtons", "")
        self.buttonBox.setObjectName("buttonBox")
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame.raise_()
        self.label_1.raise_()
        self.checkBox.raise_()
        self.lineEdit_1.raise_()
        self.label.raise_()
        self.pushButton_1.raise_()
        self.label_2.raise_()
        self.radiobutton_1.raise_()
        self.radiobutton_2.raise_()
        self.radiobutton_3.raise_()
        self.radiobutton_4.raise_()
        self.buttonBox.raise_()
        self.label.setBuddy(self.lineEdit_1)

        self.retranslateUi(dialog)
        self.pushButton_1.clicked.connect(self.lineEdit_1.clear)
        self.radiobutton_5.clicked.connect(self.radiobutton_4.show)
        self.radiobutton_5.clicked.connect(self.radiobutton_3.show)
        self.radiobutton_5.clicked.connect(self.radiobutton_2.show)
        self.radiobutton_5.clicked.connect(self.radiobutton_1.show)
        self.radiobutton_6.clicked.connect(self.radiobutton_1.hide)
        self.radiobutton_6.clicked.connect(self.radiobutton_2.hide)
        self.radiobutton_6.clicked.connect(self.radiobutton_3.hide)
        self.radiobutton_6.clicked.connect(self.radiobutton_4.hide)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        dialog.setTabOrder(self.lineEdit_1, self.pushButton_1)
        dialog.setTabOrder(self.pushButton_1, self.radiobutton_1)
        dialog.setTabOrder(self.radiobutton_1, self.radiobutton_2)
        dialog.setTabOrder(self.radiobutton_2, self.radiobutton_3)
        dialog.setTabOrder(self.radiobutton_3, self.radiobutton_4)
        dialog.setTabOrder(self.radiobutton_4, self.checkBox)
        dialog.setTabOrder(self.checkBox, self.radiobutton_5)
        dialog.setTabOrder(self.radiobutton_5, self.radiobutton_6)
        dialog.setTabOrder(self.radiobutton_6, self.comboBox_1)
        dialog.setTabOrder(self.comboBox_1, self.comboBox_2)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Find Options"))
        self.radiobutton_5.setText(_translate("dialog", "Normal"))
        self.radiobutton_6.setText(_translate("dialog", "Regular expression"))
        self.label_1.setText(_translate("dialog", "Mode"))
        self.checkBox.setText(_translate("dialog", "Match case"))
        self.label.setText(_translate("dialog", "&Find ?"))
        self.pushButton_1.setText(_translate("dialog", "X"))
        self.label_2.setText(_translate("dialog", "Search Limits"))
        self.radiobutton_1.setText(_translate(
            "dialog", "Raw Search                     (Literal search - anything)"))
        self.radiobutton_2.setText(_translate(
            "dialog", "Match whole words      (Single word or phrase)"))
        self.radiobutton_3.setText(_translate(
            "dialog", "All the words                  (Somewhere in the verse)"))
        self.radiobutton_4.setText(_translate(
            "dialog", "Any of the words           (With results sorted)"))


# Compatibility alias: some generators name the class Ui_Dialog
# Keep both names available to avoid import mismatches between modules.
Ui_Dialog = UiDialog
